function tune_vr_with_param_file(filename)
data=read_config_file(filename)
    tune_vr(str2double(data.pha),str2double(data.rll),str2double(data.vin),str2double(data.vramp),...
    str2double(data.f0),str2double(data.PHmarg),str2double(data.lout),str2double(data.rout),...
    str2double(data.VID),data.touchstoune_file,data.includePath,data.comp_file)